spring.application.name=trovebazaar-api
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${POSTGRES_DB_NAME}
spring.datasource.username=${POSTGRES_DB_USER}
spring.datasource.password=${POSTGRES_DB_PASSWORD}